### PR TITLE
chore: Add changelog check action

### PR DESCRIPTION
**Pull request by malachi-constant**
### Workflow
- Checks Pull Requests for `CHANGELOG.md` update

Failure would look like the below..

Screenshot 2024-07-18 at 10 33 10 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: IDFModuleTestsInfrastructur-59JoFoVH64CI
* Commit ID: 53d057374c23a6a52f1baae7bbce23296dad60ca
* Result: SUCCEEDED
* [Build Logs](https://mz6i2qapub.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=97c9a489-7528-42d6-ad98-3101e5d7f1ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by srinivasreddych — APPROVED** [review]

**Comment by LeonLuttenberger** [comment]
Does this have a mechanism to ignore the PRs made by Dependabot? I don't think we need a changelog entry for most of those.

**Comment by malachi-constant** [comment]
> Does this have a mechanism to ignore the PRs made by Dependabot? I don't think we need a changelog entry for most of those.

I think i'll just make a version of this that we manage, that way we can put in exemptions for authors/labels.

**Comment by malachi-constant** [comment]
Will reopen with a custom action.

**Pull request closed without merging**
