### PR TITLE
feat: adding integration tests for ecr module

### PR DESCRIPTION
**Pull request by malachi-constant**
- Adds integration test for ECR module.
- Adds `removal_policy` parameter to `ECRStack()` construct.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: IDFModuleTestsInfrastructur-59JoFoVH64CI
* Commit ID: 11cade9ff7c3ee5187c089d7fd874b1140fca606
* Result: SUCCEEDED
* [Build Logs](https://mz6i2qapub.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c56a32e1-d629-402b-ac9e-7ee62b6945f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by dgraeber — COMMENTED** [review]
Looks like the retention policy was added as a parameter to stacks.py, but I don't see support to pass it from app.py ?

**Review by dgraeber — CHANGES_REQUESTED** [review]
Please see my previous review?

**Comment by malachi-constant** [comment]
@dgraeber 
> Looks like the retention policy was added as a parameter to stacks.py, but I don't see support to pass it in app.py ?

The [IntegTests](https://docs.aws.amazon.com/cdk/api/v2/docs/integ-tests-alpha-readme.html) construct passes in `test_cases` of `type: cdk.Stack` so I don't think there's any way to run from the entrypoint (`app.py`). An alternative would require running a `cdk deploy` of the entire module and hardcoding any parameter variation instead of using the package. 

I think the best approach is just to replicate what's happening in `app.py` by setting parameters for the test, as this is essentially all that happens in that file.

**Review by dgraeber — APPROVED** [review]

**Pull request merged**
